"""Corrigiendo errores en ForeignKey

Revision ID: 10ac0746ad4f
Revises: 
Create Date: 2025-03-02 18:14:42.709664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ac0746ad4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.Column('group_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('rolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_name', sa.String(length=20), nullable=False),
    sa.Column('roll_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_name')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=20), nullable=False),
    sa.Column('field_description', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=20), nullable=False),
    sa.Column('resource_description', sa.Text(), nullable=False),
    sa.Column('resource_url', sa.Text(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_name')
    )
    op.create_table('niveles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel_name', sa.String(length=20), nullable=False),
    sa.Column('nivel_description', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel_name')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ask_title_group', sa.Text(), nullable=True),
    sa.Column('ask_name', sa.Text(), nullable=False),
    sa.Column('answer1', sa.Text(), nullable=False),
    sa.Column('answer2', sa.Text(), nullable=False),
    sa.Column('answer3', sa.Text(), nullable=True),
    sa.Column('answer4', sa.Text(), nullable=True),
    sa.Column('answer5', sa.Text(), nullable=True),
    sa.Column('answer6', sa.Text(), nullable=True),
    sa.Column('answer7', sa.Text(), nullable=True),
    sa.Column('answer8', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('ask_description', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveles.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempt_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userquizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=False),
    sa.Column('user_date', sa.DateTime(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userquizzes')
    op.drop_table('quiz_attempt_question')
    op.drop_table('quizzes')
    op.drop_table('niveles')
    op.drop_table('resources')
    op.drop_table('quiz_attempts')
    op.drop_table('users')
    op.drop_table('fields')
    op.drop_table('rolls')
    op.drop_table('groups')
    # ### end Alembic commands ###
