"""Add password hash to User model

Revision ID: a574e09fe8de
Revises: 10ac0746ad4f
Create Date: 2025-03-03 12:14:26.731203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a574e09fe8de'
down_revision = '10ac0746ad4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_constraint('fields_field_name_key', type_='unique')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('resource_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('resource_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_unique_constraint('fields_field_name_key', ['field_name'])

    # ### end Alembic commands ###
